# Generated by Django 4.1 on 2022-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('T', 'Trending'), ('N', 'New'), ('L', 'Limited')], max_length=1, null=True),
        ),
    ]
