# Generated by Django 4.1 on 2022-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_zip_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
