# Generated by Django 4.1 on 2022-10-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address_samebillingnshipping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
