# Generated by Django 4.1 on 2022-10-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
