# Generated by Django 4.1 on 2022-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_item_image_item_image_url_wishlist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Ac', 'Accessories'), ('Ch', 'Chill'), ('Co', 'Corporate'), ('Dn', 'Dinner'), ('Wt', 'Weather'), ('P', 'Party')], max_length=2),
        ),
    ]
