# Generated by Django 2.2 on 2022-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220915_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='AlexHunter', max_length=20),
            preserve_default=False,
        ),
    ]
