# Generated by Django 2.2 on 2022-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_stripeprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stripe_Price',
        ),
    ]
