# Generated by Django 2.2 on 2022-09-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220920_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
