# Generated by Django 2.2 on 2022-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20220921_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
