# Generated by Django 2.2 on 2022-09-21 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_stripeprice_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeprice',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='stripeprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.StripePrice'),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
