# Generated by Django 2.2 on 2022-09-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20220921_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripeprice',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.StripePrice'),
        ),
    ]
