# Generated by Django 2.2 on 2022-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20220921_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
