# Generated by Django 2.2 on 2022-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_payment_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
