# Generated by Django 2.2 on 2022-09-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20220923_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=679, max_length=10),
            preserve_default=False,
        ),
    ]
